be14-fin-Clover-Salad/be14-fin-Clover-Salad-BE

src/main/java/com/clover/salad/common/temp.txt

원격 repo에 develop 브랜치 등록용 임시 파일 추가

[Env] 원격 repo에 develop 브랜치 등록

---

db/SaladERP.sql

close #14 
Customers 테이블의 'birthdate' 컬럼의 제약 조건을 not null → null로 수정

[Fix] 고객 테이블의 'birthdate' 컬럼 제약 조건 수정

---

.gitignore
build.gradle
db/SaladERP.sql
src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
src/main/java/com/clover/salad/product/command/application/dto/ProductDTO.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java
src/main/java/com/clover/salad/product/command/domain/aggregate/entity/Product.java
src/main/java/com/clover/salad/product/command/domain/repository/ProductRepository.java
src/main/java/com/clover/salad/product/query/controller/ProductQueryController.java
src/main/java/com/clover/salad/product/query/mapper/ProductMapper.java
src/main/java/com/clover/salad/product/query/service/ProductQueryService.java
src/main/java/com/clover/salad/product/query/service/ProductQueryServiceImpl.java
src/main/resources/application.properties
src/main/resources/com/clover/salad/product/query/mapper/ProductMapper.xml

close #8 
Feature: 상품 추가 기능 구현

[Feature] 상품 추가 기능 구현

---

src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java

close #25 
close #26 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
상품의 상세정보를 수정하는 기능 구현
상품을 삭제(논리)하는 기능 구현

[Feat] 상품 수정/삭제 기능 구현

---

.vscode/settings.json
bin/main/com/clover/salad/common/temp.txt
bin/main/com/clover/salad/customer/query/mapper/CustomerMapper.xml
bin/main/com/clover/salad/product/query/mapper/ProductMapper.xml
gradle.properties
src/main/java/com/clover/salad/SaladApplication.java
src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
src/main/java/com/clover/salad/customer/command/application/dto/CustomerDTO.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
src/main/java/com/clover/salad/customer/command/domain/repository/CustomerRepository.java
src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml

close #18 
close #22
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 고객 더미 데이터 전체 조회
- 특정 id에 해당하는 고객만 조회
>

[Feat] 고객 목록/상세 조회 기능 구현

---

db/SaladERP.sql

> close #127 
> email 컬럼 추가
> 관리자 여부 컬럼 추가
> 사번, 연락처 컬럼에 Unique 제약 조건 추가

[Feat] employee 테이블 관련 db 제약조건 변경사항 업데이트

---

db/Dummy.sql
src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/DepartmentEntity.java
src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/FileUploadEntity.java
src/main/java/com/clover/salad/employee/command/domain/aggregate/enums/EmployeeLevel.java
src/main/java/com/clover/salad/employee/command/domain/aggregate/enums/EmployeeLevelConverter.java
src/main/java/com/clover/salad/employee/query/controller/EmployeeQueryController.java
src/main/java/com/clover/salad/employee/query/dto/DepartmentQueryDTO.java
src/main/java/com/clover/salad/employee/query/dto/EmployeeQueryDTO.java
src/main/java/com/clover/salad/employee/query/dto/SearchEmployeeDTO.java
src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml

> close #111 , close #112 , close #129 
> 1. 사원 전체조회 기능
> 2. 사원 조건 검색 기능
1. 사원 전체조회 기능
2. 사원 조건 검색 기능

[Feat] 사원 전체 조회, 조건으로 검색 기능 구현

---

db/Dummy.sql

[Style] Dummy.sql 정리

---

db/SaladERP.sql

> close #135 
> 1. Approval 테이블 code 컬럼에 Unique 제약조건 추가
> 2. code, title, state, comment의 varchar 크기 조정

[Env] 결재 코드에 unique 제약 조건 추가

---

src/main/java/com/clover/salad/common/WebConfig.java
src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
src/main/java/com/clover/salad/goal/command/application/service/GoalCommandService.java
src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
src/main/java/com/clover/salad/goal/command/domain/repository/GoalRepository.java
src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml

close #119 
close #120 
실적 목표 수정 기능 구현
실적 목표 수정 시 연간 목표 조회 기능 구현
실적 목표 삭제 기능 구현
실적 목표 수정 기능
실적 목표 수정 시 연간 목표 조회 기능
실적 목표 삭제 기능

[Feat] 실적 목표 수정/삭제 기능 구현

---

src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
src/main/java/com/clover/salad/contract/command/controller/ContractUploadController.java
src/main/java/com/clover/salad/contract/command/dto/ContractUpdateRequestDTO.java
src/main/java/com/clover/salad/contract/command/dto/ContractUpdateResponseDTO.java
src/main/java/com/clover/salad/contract/command/service/ContractService.java

close #72 
계약 테이블 안에 있는 비고란 수정시 다른 데이터들 변경하지 않고 PatchMapping을 통하여 비고란 수정
>

[Feature] 계약 수정 기능 함수 구현

---

src/main/java/com/clover/salad/common/exception/EmployeeNotFoundException.java
src/main/java/com/clover/salad/common/exception/GlobalExceptionHandler.java
src/main/java/com/clover/salad/common/exception/InvalidSearchTermException.java
src/main/java/com/clover/salad/common/exception/UnauthorizedEmployeeException.java
src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
src/main/java/com/clover/salad/goal/command/application/dto/DeptSearchTermDTO.java
src/main/java/com/clover/salad/goal/command/application/dto/EmployeeSearchTermDTO.java
src/main/java/com/clover/salad/goal/command/application/service/GoalCommandService.java
src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml

close #157 
close #158 
Refactor: 토큰으로 현재 사용자를 가져오는 로직 적용
Refactor: 실적 목표 조회 기능 수정
- 프론트에서 실제로 들어올 정보에 맞게 수정
- 개인 실적 목표 조회에서 받는 조건 수정(직급, 이름 -> 사원 코드)
- 직급, 이름으로는 한 명으로 특정되지 않는 경우가 있을 수 있음

[Refactor] 토큰으로 현재 사용자를 가져오는 로직 적용

---

src/main/java/com/clover/salad/sales/command/domain/aggregate/entity/SalesEntity.java
src/main/java/com/clover/salad/sales/query/controller/SalesQueryController.java
src/main/java/com/clover/salad/sales/query/dto/SalesQueryRequestDTO.java
src/main/java/com/clover/salad/sales/query/dto/SalesQueryResponseDTO.java
src/main/java/com/clover/salad/sales/query/mapper/SalesQueryMapper.java
src/main/java/com/clover/salad/sales/query/service/SalesQueryService.java
src/main/java/com/clover/salad/sales/query/service/SalesQueryServiceImpl.java
src/main/resources/com/clover/salad/sales/query/mapper/SalesQueryMapper.xml

> close #76 
> 매출 조건 검색 및 전체 조회 기능 구현
- 매출 조회 및 검색 기능
- 금액, 날짜 조건 범위 검색
- 음수 금액 방지 조건 
1. 조건 일부 넣고 검색
2. 조건 없이 검색
>

[Feat] 매출 내역 조회 기능 구현

---

src/main/java/com/clover/salad/contract/query/controller/ContractController.java
src/main/java/com/clover/salad/contract/query/dto/ContractDTO.java
src/main/java/com/clover/salad/contract/query/dto/ContractSearchDTO.java
src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
src/main/java/com/clover/salad/contract/query/service/ContractService.java
src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml

close #188 
- CustomerId 추가 계약 조회시 다른 곳에서 CustomerId 사용하기 위한 수정
- 검색 조건에서 amount 이상 이하 기능 빠져있어 추가
- 검색 조건 between and 에서 각각 분리하여 수정
>

[Refactor] 계약 조회시 CustomerID 추가

---

src/main/java/com/clover/salad/contract/query/controller/ContractController.java
src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
src/main/java/com/clover/salad/contract/query/service/ContractService.java
src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml

close #209 
- 게약 id로 조회하여 해당 계약이 존재하는지 확인하는 기능
- 계약 목록에서 사원 id 기준으로 가진 고객 pk들 확인하는 기능
- boolean타입으로 true false로 반환됩니다.
- List형태로 반환됩니다

[Feat] 요청한 다른 도메인 조회 구현

---

src/main/java/com/clover/salad/employee/query/dto/EmployeeDetailDTO.java
src/main/java/com/clover/salad/performance/command/application/controller/PerformanceCommandController.java
src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java
src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml

> close #220 
> 사원 상세 조회시 필요한 dto 내부에 사진이 없어서 누락된 사진 추가
>

[Refactor] 누락된 dto 필드 추가

---

src/main/java/com/clover/salad/employee/query/dto/EmployeeDetailDTO.java
src/main/java/com/clover/salad/employee/query/dto/EmployeeSearchResponseDTO.java
src/main/java/com/clover/salad/employee/query/dto/LoginHeaderInfoDTO.java
src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml

> close #240 
> 사원 검색 및 모달창 구현을 위한 dto 수정(사원 id 추가)
>

[Refactor] 사원 검색 및 모달창 구현을 위한 dto 수정

---

src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java

> close #232 
> 결재 요청 시 해당 계약이 있는지 체크하는 로직 추가
>

[Feat] 결재 요청 시 해당 계약이 존재하는지 체크하는 로직 추가

---

src/main/java/com/clover/salad/contract/document/entity/DocumentTemplate.java
src/main/java/com/clover/salad/documentTemplate/command/application/controller/DocumentTemplateCommandController.java
src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateDTO.java
src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplatePatchRequestDTO.java
src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandService.java
src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
src/main/java/com/clover/salad/documentTemplate/command/domain/repository/DocumentTemplateCommandRepository.java
src/main/java/com/clover/salad/documentTemplate/query/controller/DocumentTemplateQueryController.java
src/main/java/com/clover/salad/documentTemplate/query/dto/DocumentTemplateSearchDTO.java
src/main/java/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.java
src/main/java/com/clover/salad/documentTemplate/query/service/DocumentTemplateQueryService.java
src/main/java/com/clover/salad/documentTemplate/query/service/DocumentTemplateQueryServiceImpl.java
src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
src/main/resources/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.xml

close #101 #103 #104 #100  
계약서 수정
계약서 삭제
계약서 전체조회
계약서 특정 한건 조회
계약서 조건별 조회
>

[Feat] : 계약서 양식 수정 삭제 조회

---

src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
src/main/java/com/clover/salad/product/command/application/dto/ProductDTO.java
src/main/java/com/clover/salad/product/command/application/dto/ProductImageDTO.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java
src/main/java/com/clover/salad/product/query/controller/ProductQueryController.java
src/main/resources/com/clover/salad/product/query/mapper/ProductMapper.xml

close #246
close #247
상품의 이미지를 등록하고 등록된 이미지를 표시할 수 있도록 경로를 받아오게 코드 수정

[Feat] 상품 이미지 등록/조회 기능 추가

---

.ebextensions/app.config
.github/workflows/prod-deploy.yml
.gitignore
.platform/nginx.conf
Procfile
build.gradle

> githubActions를 통한 CI/CD 배포 설정 파일
>

[Env] GitActions 및 CI/CD 설정

---

src/main/java/com/clover/salad/common/file/service/FileUploadService.java
src/main/java/com/clover/salad/common/file/service/S3Uploader.java
src/main/java/com/clover/salad/contract/command/facade/ContractUploadFacade.java
src/main/java/com/clover/salad/contract/command/service/ContractService.java
src/main/java/com/clover/salad/contract/command/service/parser/PdfContractParserService.java
src/main/java/com/clover/salad/contract/document/service/DocumentOriginService.java

기존 로컬에서 저장하던 방식에서 S3으로 변경
프론트도 제 브랜치에서 해야 작동합니다

[Refactor] 계약 업로드 S3 방식으로 수정

---

db/SaladERP.sql
src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
src/main/java/com/clover/salad/common/file/service/PdfThumbnailService.java
src/main/java/com/clover/salad/common/logging/controller/AccessLogController.java
src/main/java/com/clover/salad/common/logging/dto/AccessLogDTO.java
src/main/java/com/clover/salad/contract/command/dto/ContractDTO.java
src/main/java/com/clover/salad/contract/command/facade/ContractUploadFacade.java
src/main/java/com/clover/salad/contract/command/service/ContractService.java
src/main/java/com/clover/salad/contract/query/dto/ContractResponseDTO.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml

[Feat] 로그 조회 구현

---

src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
src/main/java/com/clover/salad/goal/command/application/dto/EmployeeSearchTermDTO.java
src/main/java/com/clover/salad/goal/command/application/dto/GoalDTO.java
src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml

DTO 속성 타입 수정
기본 실적 목표 조회용 엔드포인트 생성
실적 목표 수정 URI 변경

[Refactor] 실적 목표 프론트엔드 진행 중 수정사항

---

src/main/java/com/clover/salad/common/WebConfig.java

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
프론트 DNS CORS 설정 추가
>

[Env]프론트 CORS 설정 추가

---

db/Dummy.sql

고객, 상담 더미 수정
- DELETE FROM CUSTOMER/CONSULTATIOM 후 INSERT하도록 했습니다.

[Chore] 고객, 상담 더미 수정

---

src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java

[Refactor] 고객 삭제 기능 추가 및 PR 반영

---

src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java

[Refactor] : 계약 반려 적용

---

src/main/java/com/clover/salad/common/util/AuthUtil.java
src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml

- 상담/고객 도메인 FE에 BE 연결하는 과정에서 query단 조회 로직 수정

[Refactor] 상담/고객 프론트 연결

---

src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
src/main/java/com/clover/salad/common/file/enums/FileUploadType.java
src/main/java/com/clover/salad/common/file/service/S3PathResolver.java
src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateDTO.java
src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
src/main/resources/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.xml

Feat : 계약서 양식 버그 수정 및 썸네일등록

---

src/main/java/com/clover/salad/consult/command/application/controller/ConsultationCommandController.java
src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
src/main/java/com/clover/salad/consult/query/dto/ConsultQueryDTO.java
src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml

- 상담 관리 프론트엔드 연결 중 상담 상세 내역 조회를 하기 위해 백엔드 조회 로직 수정

[Refactor] 상담 관리 프론트 연결을 위한 로직 수정

---

db/SaladERP.sql

더미 데이터 수정으로 인한 테이블 속성(customer_feedback_score) 수정

Chore: 실적 목표 관련 더미 데이터 추가로 인한 테이블 수정

---

src/main/java/com/clover/salad/common/WebConfig.java
src/main/java/com/clover/salad/notification/query/controller/NotificationQueryController.java
src/main/java/com/clover/salad/notification/query/mapper/NotificationMapper.java
src/main/java/com/clover/salad/notification/query/service/NotificationQueryService.java
src/main/java/com/clover/salad/notification/query/service/NotificationQueryServiceImpl.java
src/main/java/com/clover/salad/notification/query/sse/SseEmitterManager.java
src/main/java/com/clover/salad/security/WebSecurity.java
src/main/resources/com/clover/salad/notification/query/mapper/NotificationMapper.xml

> close #317 
> 프론트엔드 도메인과 연동되는 실서비스 환경에서 CORS 정책에 맞는 백엔드 및 Nginx 설정을 반영하기 위한 기능
> nginx 리버시 프록시 방식에 맞도록 수정
- 실서비스 도메인(https://saladerp.com) 기준 CORS 정책 정비
- subscribe-token 요청의 credentials 문제 해결을 위한 Nginx 라우팅 세분화
- SSE(/notification/subscribe) 경로는 credentials: false로, 일반 인증 요청은 credentials: true로 분리 적용
- Spring Security 및 WebConfig 설정 충돌 여부 점검 및 주석 처리
>

[Refactor] 알림 - sse 연결 에러 수정 및 배포 환경에 맞게 cors 정책 수정

---

db/Dummy.sql

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

[refactor] 더미수정

---

src/main/java/com/clover/salad/common/WebConfig.java
src/main/java/com/clover/salad/contract/query/dto/ContractSearchDTO.java
src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
src/main/java/com/clover/salad/security/WebSecurity.java
src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml

[Feat] : 관리자일때 계약 전체 보기 함수 구현

---

src/main/java/com/clover/salad/notification/query/sse/SseEmitterManager.java

> close #321 
> 로컬 환경의 개발 단계에서는 문제가 없었던 sse 알림 기능이 배포환경에 가면서 연결이 불안정해지고
> 주기적으로 끊기는 문제가 발생. emitter가 유지되도록 개선 후 배포 환경 수정
>

[Refactor] sse 알림의 연결이 배포환경에서 유지되지 않는 문제 수정

---

src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java

[Task] 모든 권한용 고객 전체 조회

---

src/test/java/com/clover/salad/contract/document/service/DocumentOriginServiceTest.java

close #325 
계약서 원본 서비스 계층 테스트 케이스 작성 (성공, 예외상황, 오류)

[Feat] : 계약서 원본 서비스 계층 테스트 케이스 작성

---

src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java

[Task] 권한 미체크 상담 내역 조회

---

src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java

Refactor: 개인 실적 목표 갱신에 권한 필요 없는 메소드 사용하도록 변경
Refactor: 고객 만족도 점수 기간 설정
> 윤석님, 이제 결재 승인에 붙이시면 될 겁니다.
> 수지님도 상담 등록 시에 붙여주세요. 만족도 점수 있을 때만 실행되게 하면 충분할 것 같습니다.

[Refactor] 개인 실적 목표 갱신에 권한 필요 없는 메소드 사용하도록 변경

---

src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java

[Fix] 상담 목록 조건 수정

---

src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml

[Fix] 상담 팀장/관리자 권한 분기 처리

---

src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java

Refactor: 실적 목표 삭제 시 관리자 체크(프론트에 연결 없음)
Refactor: 실적 목표 조회 시 값이 없으면 204 코드 내보내도록 수정
> 값이 있으면 200 코드를 보내고, 프론트에서 코드를 통해 판단하는 로직입니다.

[Refactor] 실적 목표 QA 적용

---

src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java

[Refactor] 고객 수정, 삭제 권한 분기 제거

---

.github/workflows/prod-deploy.yml
src/test/java/com/clover/salad/consult/command/application/service/ConsultationCommandServiceImplTest.java
src/test/java/com/clover/salad/consult/query/service/ConsultQueryServiceImplTest.java
src/test/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImplTest.java
src/test/java/com/clover/salad/customer/query/service/CustomerQueryServiceImplTest.java

고객/상담 command, query 테스트 케이스 작성

[Task] 고객/상담 테스트 케이스 작성

---

src/test/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImplTest.java
src/test/java/com/clover/salad/goal/query/service/GoalQueryServiceImplTest.java
src/test/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImplTest.java
src/test/java/com/clover/salad/performance/query/service/PerformanceQueryServiceImplTest.java
src/test/java/com/clover/salad/product/command/application/service/ProductCommandServiceImplTest.java
src/test/java/com/clover/salad/product/query/service/ProductQueryServiceImplTest.java

Test: 실적 목표 테스트 코드 작성
Test: 실적 테스트 코드 작성
Test: 상품 테스트 코드 작성

[Test] 실적, 실적 목표, 상품 테스트 케이스 작성

---

src/test/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImplTest.java

[Refactor] 고객 삭제 테스트 케이스 수정
